### ISSUE TITLE
1.19.2 crash with no other mods

### ISSUE THREAD

**Issue by radiant-ai** [malte0811/FerriteCore#100]
Decided to download a bunch of performance mods and got surprised that I cannot start minecraft with a single FerriteCore:

https://paste.gg/p/anonymous/99492fa9581648aaa7a6f7e7ade9fd2f

![image](https://user-images.githubusercontent.com/43506080/200996361-836545dd-7842-4bc6-8446-90a1f9c9c5fb.png)

**Comment by malte0811** [comment]
2.1.1 is a build for 1.16.5, I released that to deal with some MC launcher changes a few days ago. You need to use 5.0.0 for Fabric 1.19.2.

**Comment by radiant-ai** [comment]
Oh... Sorry. This build got marked as main download file on curseforge and
I did not notice that.

Thank you
