### ISSUE TITLE
Canary Incompatibility on Server

### ISSUE THREAD

**Issue by CheezBallzFTW** [malte0811/FerriteCore#101]
https://gist.github.com/CheezBallzFTW/ff6fec4ad9f435a3bf618ae19de375cc

https://gist.github.com/CheezBallzFTW/0f61c133f3b71228c37fd72e35eac802

**Comment by malte0811** [comment]
Does this happen without FerriteCore? From this comment https://github.com/AbdElAziz333/Canary/issues/41#issuecomment-1309422375 and also from a quick look at the code involved it looks like a pure Canary issue.

**Comment by AbdElAziz333** [comment]
This issue is from Canary not Ferritecore.
