### ISSUE TITLE
malte0811.ferritecore.classloading.FastImmutableMapDefiner.lambda$static$0(FastImmutableMapDefiner.java:28)

### ISSUE THREAD

**Issue by ghost** [malte0811/FerriteCore#104]
> ---- Crashed! ----
> Date/Time: 2022/11/24 18:35:18.8676
> 
> -- Crash --
> 
> org.quiltmc.loader.impl.FormattedException: java.lang.ClassFormatError: Invalid ClassFile structure
> 	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
> 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473)
> 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
> 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
> 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
> 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
> Caused by: java.lang.ClassFormatError: Invalid ClassFile structure
> 	at java.lang.invoke.MethodHandles$Lookup$ClassFile.readInt(MethodHandles.java:2291)
> 	at java.lang.invoke.MethodHandles$Lookup$ClassFile.newInstance(MethodHandles.java:2241)
> 	at java.lang.invoke.MethodHandles$Lookup.makeClassDefiner(MethodHandles.java:2318)
> 	at java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:1843)
> 	at malte0811.ferritecore.classloading.FastImmutableMapDefiner.lambda$static$0(FastImmutableMapDefiner.java:28)
> 	at malte0811.ferritecore.classloading.FastImmutableMapDefiner.defineInAppClassloader(FastImmutableMapDefiner.java:71)
> 	at malte0811.ferritecore.classloading.FastImmutableMapDefiner.lambda$static$2(FastImmutableMapDefiner.java:41)
> 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
> 	at malte0811.ferritecore.classloading.FastImmutableMapDefiner.makeMap(FastImmutableMapDefiner.java:56)
> 	at malte0811.ferritecore.impl.StateHolderImpl.populateNeighbors(StateHolderImpl.java:40)
> 	at net.minecraft.state.State.createWithTable(State:551)
> 	at net.minecraft.state.StateManager.<init>(StateManager:68)
> 	at net.minecraft.state.StateManager$Builder.build(StateManager:157)
> 	at net.minecraft.block.Block.<init>(Block:187)
> 	at net.minecraft.block.AirBlock.<init>(AirBlock:12)
> 	at net.minecraft.block.Blocks.<clinit>(Blocks:103)
> 	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9)
> 	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20)
> 	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
> 	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16)
> 	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32)
> 	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21)
> 	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66)
> 	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98)
> 	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105)
> 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
> 	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104)
> 	at net.minecraft.util.registry.Registry.<clinit>(Registry:326)
> 	at net.minecraft.Bootstrap.initialize(Bootstrap:50)
> 	at net.minecraft.client.main.Main.main(Main:161)
> 	at net.minecraft.client.main.Main.main(Main:51)
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471)
> 	... 11 more
>
> - [Crash-log](https://github.com/malte0811/FerriteCore/files/10088180/crash-2022-11-24_18.35.18.8676-quilt_loader.txt)
> - [Log-file](https://github.com/malte0811/FerriteCore/files/10088183/latest.log)

**Comment by malte0811** [comment]
Downgrade Quilt to 0.17.6 for now, I'll look into why it's crashing on 0.18.1-beta.3 over the weekend.

**Comment by ghost** [comment]
alright
