### ISSUE TITLE
1.19.3 compat

### ISSUE THREAD

**Issue by SolDev69** [malte0811/FerriteCore#107]
Now that 1.19.3 is out I can finally ask for 1.19.3 compatibility, since the 1.19.2 version crashes.

**Comment by malte0811** [comment]
Fabric/Quilt releases are out now (waiting for approval on CF), Forge releases will follow once Forge releases and I can check that nothing broke.

Generally, modders will update their mods once they have time for it. In most cases that isn't in the 30 minutes after the release. I don't have a major problem with issues like this (but still don't really like them), but I know that many other modders do.
