### ISSUE TITLE
Radium Reforged Incompatibility

### ISSUE THREAD

**Issue by Superniquito** [malte0811/FerriteCore#109]
java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config;
responsible mod [Radium Reforged](https://www.curseforge.com/minecraft/mc-mods/radium-reforged)
[latest.log](https://github.com/malte0811/FerriteCore/files/10233592/latest.log)

**Comment by malte0811** [comment]
See https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397
