### ISSUE TITLE
compatibility question

### ISSUE THREAD

**Issue by SniffSniff125** [malte0811/FerriteCore#112]
i'm currently playing minecraft 1.19.2 forge, im lagging even with really good pc (rtx 3060).
so i wanted to try this mod, but i dont know if it is compatible with rubidium (forge sodium). and i dont want to risk damaging some configs.

**Comment by malte0811** [comment]
A lot of people have been using it with Rubidium (and with sodium on Fabric), so it should work without issues. I'm not aware of any other incompatibilities either, other than a soft one with Radium (see https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397).
