### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by jacklollz2** [malte0811/FerriteCore#115]
The contents of this have been erased.

**Comment by malte0811** [comment]
I'm unable to reproduce this from a quick test. Please upload the full log to https://gist.github.com (and post the link here), including the modlist logged at the start.

**Comment by jacklollz2** [comment]
I'll see what I can do to troubleshoot this

**Comment by jacklollz2** [comment]
Caused by PurPurClient.
https://hastebin.com/share/fisihotaga.ruby

**Comment by malte0811** [comment]
For some reason PurpurClient includes guava (a library) via Jar-In-Jar, even though it's part of MCs own dependencies, and the version they include is the same one MC depends on. That causes the code that allows me to define new `ImmutableMap` classes to fail. I'm not 100% sure on the failure cause here yet, it may be a bug in Quilt. But the easiest fix will probably be for PC to stop including guava (there's no reason to AFAICT). I'll open an issue on their end some time this week, I don't have time to write up something for them right now.

**Comment by malte0811** [comment]
See linked Purpur issue.
