### ISSUE TITLE
Mixin warning: is public and should be specified in value

### ISSUE THREAD

**Issue by TheDGOfficial** [malte0811/FerriteCore#12]
Hi, I know this does not cause any issues, but solving warnings is always good.

```
@Mixin target net/minecraft/class_4970$class_4971$class_3752 is public in ferritecore.blockstatecache.mixin.json:BlockStateCacheAccess and should be specified in value
```

Maybe you can solve this? I don't know much about Mixin but you probably need to add `@Public` or something together with `@Mixin`.

**Comment by vktec** [comment]
Fabric is lying. That class is `net.minecraft.block.AbstractBlock.AbstractBlockState.ShapeCache` and is defined package-private.

**Comment by malte0811** [comment]
Exactly. My guess is that something is making it public at runtime (maybe some access widener?), it certainly isn't public at build-time, which is what matters.

I agree that it's generally a good idea to fix as many warnings as possible, but in this case the warning seems to be a false positive. If there was some exclusion list of "I know you (Mixin) think this wrong, I actively disagree" I'd add it there, but as there isn't one (AFAICT) the warning will just have to stay.
