### ISSUE TITLE
1.19.2 Near Instant Crash on Startup

### ISSUE THREAD

**Issue by jadenquinn** [malte0811/FerriteCore#137]
I have a few other optimization mods installed, I'm attempting to figure out what combonation of them will make a light modded server run best on a 2012 12-core Mac Pro. I got a warning on my client that memory usage would be very high unless I installed FerriteCore, however when I did this, I was gifted this crash: https://pastebin.com/sCFAPRK3
That's the crash log from the server, the client one looks identical. It's just the server one I had on hand on this machine since this is the machine the server is running on, and I decided for some reason to open Github on THAT.

**Comment by embeddedt** [comment]
Remove Radium.

**Comment by malte0811** [comment]
^That, see https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397.
