### ISSUE TITLE
1.20.2 Crash On Startup

### ISSUE THREAD

**Issue by SlayDigger** [malte0811/FerriteCore#138]
Upon attempting to load forge FerriteCore 6.0.1 I was gifted with exit code -1, and this is the log: https://pastebin.com/wDfRLhVS

**Comment by malte0811** [comment]
One of your other mods has a bug (loads a class far too early), but this is not something you can debug yourself (other than using a binary search). What would be the easiest way for me to reproduce this? It looks like this was some development version of your pack, and it does not happen with either 1.1 or 1.3 for me.

**Comment by SlayDigger** [comment]
I did end up resolving this issue after I believe. Pretty certain it was piglin proliferation
