### ISSUE TITLE
A mod tried to access the state neighbor table directly (1.20.1)

### ISSUE THREAD

**Issue by DangerMage** [malte0811/FerriteCore#147]
Modpack was working, then it started crashing on startup with this log:

https://paste.ee/p/sUb00

(log contains the mod list, java version, forge version, minecraft version, JVM arguments, etc)

**Comment by DangerMage** [comment]
Looks like I was missing a dependency (https://www.curseforge.com/minecraft/mc-mods/astikor-carts-redux)

probably a bug that it crashes instead of going to the missing dependencies screen

**Comment by davidromrell** [comment]
seems to be a bug with canary Imo, although for sure it is an optimization mod.

**Comment by malte0811** [comment]
Forge/NeoForge have some strange behavior relating to Mixins and "early loading errors" (which includes missing dependencies); I don't think I can do much about this on my end.
