### ISSUE TITLE
New logo/Thumbnail?

### ISSUE THREAD

**Issue by Quantodeluz** [malte0811/FerriteCore#151]
When i first saw the mod, i didn't know what the thumbnail meant, and when i saw the explanation and the wikipedia page, i tought "why didn't he made at least a more pixelated version? this doesn't look like a logo", so i decided to make a more minecraft-y version, and i came up with this:

![FerriteCore big Logo](https://github.com/malte0811/FerriteCore/assets/128737665/92f96361-de3d-4117-b9e2-00b775c9a15f)

If anyone could upload it, i would like it a lot.
(Sorry for the bad english, i'm not a native speaker)

**Comment by Quantodeluz** [comment]
I'm also working on a gallery image version, with more cores.

**Comment by Quantodeluz** [comment]
uhhh... hello? @malte0811 , do you like this?

**Comment by malte0811** [comment]
Sorry, I am not interested in changing the logo. For this sort of thing you should generally contact the mod dev before you put any work into it.
