### ISSUE TITLE
FPS decrease 

### ISSUE THREAD

**Issue by 13Ralef** [malte0811/FerriteCore#153]
Idk why is it but ferrite core decreases my fps in servers, I personally don't use many mods, just like 50 (that's so little)
And it's really not helping with fps as it should.

**Comment by malte0811** [comment]
Without any further information it is impossible to know what is causing this.
- What version of Minecraft and FerriteCore are you using? Are you on NeoForge, Fabric, or Forge?
- What other mods are you using?
- Please install [Spark](https://www.curseforge.com/minecraft/mc-mods/spark), run its CPU profiler both with and without FerriteCore and send me the results.
