### ISSUE TITLE
crash in 1.16 dev-env using parchment mappings

### ISSUE THREAD

**Issue by AnAwesomGuy** [malte0811/FerriteCore#157]
[crash](https://github.com/malte0811/FerriteCore/files/14811208/crash-2024-03-30_16.22.16-client.txt)
link to repo: https://github.com/AnAwesomGuy/bosstools-performance

**Comment by malte0811** [comment]
You probably need to add [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/63fb2644cda6acc644a1a6dfdff0f24cd91db9d9/build.gradle#L109-L110) to your run configs.

**Comment by AnAwesomGuy** [comment]
the mixin is marked as `remap = false`, removing it from the refmap, and I also already have mixingradle, which makes that fix obsolete (disabling that mixin from the config works fine)

**Comment by malte0811** [comment]
Ah, I did not notice it was "that" mixin. I thought I had explicitly listed all the "common" names of that method, Parchment should have `getQuads`. I'm not sure what is happening, but I do not plan to release a new 1.16.5 build in any case.
