### ISSUE TITLE
The game crashes when starting in version 1.20.5 

### ISSUE THREAD

**Issue by J4PC** [malte0811/FerriteCore#159]
![image](https://github.com/malte0811/FerriteCore/assets/97805057/ba2c3cd2-0f36-42b4-8971-6f3815b07e60)

> The game crashed whilst bootstrap
> Error: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2688 failed

farbic-loader-0.15.10-1.20.5 using the mods:
- ferritecore-6.0.3-fabric
- fabric-api-0.97.6+1.20.5

**Comment by malte0811** [comment]
Yes, MC made some changes that were incompatible with the old FerriteCore build. I have released 6.1.0 for MC 1.20.5.
