### ISSUE TITLE
Not sure if it's this mod causing server crash (Ticking World)

### ISSUE THREAD

**Issue by varencilator** [malte0811/FerriteCore#17]
It was working fine for quite a while

[crash-2021-05-07_15.46.48-server.txt](https://github.com/malte0811/FerriteCore/files/6443986/crash-2021-05-07_15.46.48-server.txt)
[crash-2021-05-07_09.18.07-server.txt](https://github.com/malte0811/FerriteCore/files/6443987/crash-2021-05-07_09.18.07-server.txt)

**Comment by malte0811** [comment]
I'll look into it in detail tomorrow, right now it looks like a bug in [Puddles](https://github.com/TeamMidnightDust/Puddles/blob/0342b5f3128a2ce5a545f47e0c170ce863d8af9e/src/main/java/eu/midnightdust/puddles/mixin/MixinServerWorld.java#L51-L61) to me. But the error message definitely needs to be improved (which is a problem on my side).

**Comment by varencilator** [comment]
Thanks, I'm pretty sure it's puddles or at least not related to Ferritecore because crash happened even without. Also, noticed it happens while it's raining.

**Comment by varencilator** [comment]
Unrelated (was issue with Puddles mod, fixed in release 1.1.0)
