### ISSUE TITLE
Mod compatibility issues with Lithium's Neoforge Port and Package Rename

### ISSUE THREAD

**Issue by 2No2Name** [malte0811/FerriteCore#173]
There will be new compatibility issues, because

1. Lithium renamed its packages to `net.caffeinemc.mods.lithium.common` [Possibly relevant code](https://github.com/malte0811/FerriteCore/blob/e26af6babcd8d229ac113e265c0826af961088e8/Common/src/main/java/malte0811/ferritecore/mixin/config/FerriteMixinConfig.java#L25)
2. Lithium will release a neoforge port in the future (No more specific issues known yet)

**Comment by malte0811** [comment]
1. I will adjust the package name, but since the only feature where this is relevant is disabled by default (strange non-reproducible crashes I cannot explain) it is not critical.
2. I will add the necessary code on the NF side of FC. Are there builds for testing available, or do I need to build it myself?

**Comment by 2No2Name** [comment]
There are the github actions builds from https://github.com/CaffeineMC/lithium-fabric/pull/566 , releases will be made after some releases that are marked as beta or so.

I have one report of a user mentioning the neighbor table issue, where lithium is accessing the uninitialized neighbor table.

**Comment by malte0811** [comment]
Yes, that is the issue I expected. On Fabric I disable the relevant Lithium mixin, I have added the same on Neo now. Test builds should be available [here](https://github.com/malte0811/FerriteCore/actions/runs/11305853867/job/31445795896) soon.

Do you expect the Neo version of Fabric to be "fully" released on 1.21.1, or do you think that will only happen in 1.21.2 and above?

**Comment by 2No2Name** [comment]
I haven't made a decision on that, backports to even older versions may be possible as well.

**Comment by 2No2Name** [comment]
@malte0811 Sorry, I forgot to notify you about the beta release. I see you are already fixing compatibility issues. I can also implement changes on lithium's side to avoid you having to make a new release for 1.21.1 . I guess it means disabling a few lithium settings by default when ferritecore is present

**Comment by 2No2Name** [comment]
Closing this as https://github.com/malte0811/FerriteCore/issues/175 and https://github.com/malte0811/FerriteCore/issues/174 are more detailed.

**Comment by malte0811** [comment]
I've created a new 1.21.1 build with the fix, now waiting for CF to approve it. I usually do not have time for modding during the week, so most things that pop up during the week have to wait until the weekend.
