### ISSUE TITLE
FerriteCore crash with Lithium (NeoForge 1.21.1)

### ISSUE THREAD

**Issue by chiefjazzdiewltr** [malte0811/FerriteCore#175]
Minecraft Version: 1.21.1
Modloader: NeoForge 21.1.72

When using FerriteCore 7.0.0 with Lithium 0.14.0 it crashes giving me the error shown in here: [crashlog](https://mclo.gs/L8dN9Nl)
Mentioning something about state neighbor tables and to report it here.

**Comment by 2No2Name** [comment]
Duplicate of https://github.com/malte0811/FerriteCore/issues/174

**Comment by piotrbulkowski** [comment]
Fixed in the artifact 87 build, just copy the output jar to mods folder and you're good to go
https://github.com/malte0811/FerriteCore/actions/runs/11371242578

**Comment by malte0811** [comment]
I've created a new 1.21.1 build with the fix, now waiting for CF to approve it.
