### ISSUE TITLE
duped files on cf?

### ISSUE THREAD

**Issue by VaporeonScripts** [malte0811/FerriteCore#177]
![image](https://github.com/user-attachments/assets/4c6c0927-9c77-45c9-a819-78cc9be2a603)
lol

**Comment by malte0811** [comment]
Should be gone now. I was trying to set up automatic uploads, and apparently the plugin ignored the `dryRun` setting that is meant to not upload anything…

**Comment by VaporeonScripts** [comment]
oh lmao, good
