### ISSUE TITLE
Version 7.0.2 Fabric Crashing

### ISSUE THREAD

**Issue by Quetzalis** [malte0811/FerriteCore#178]
The game crashed whilst bootstrap
Error: java.lang.ExceptionInInitializerError
Exit Code : -1

Also tested with minimal mods - only Fabric API and FerrriteCore. Still crashing with the same error.

**Comment by malte0811** [comment]
Ah, the automatic release code is uploading the wrong jar. I'll fix that in a moment.

**Comment by malte0811** [comment]
I have uploaded fixed versions of both 7.0.2 and 7.1.0.

**Comment by Quetzalis** [comment]
Alright thanks :)

**Comment by suerion** [comment]
Thanks for the fast fix :)
