### ISSUE TITLE
Will this be updated to 1.17?

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [malte0811/FerriteCore#18]

**Comment by malte0811** [comment]
Yes. I'm a little busy right now, but I hope to get around to it on the weekend or so. Maybe by that time Forge will be "ready enough" for this type of mod (nearly pure Mixins) as well.

**Comment by malte0811** [comment]
I've published a beta build for 1.17 (only on Fabric for now), see:  
https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric/files/3360116 (not approved yet)  
https://modrinth.com/mod/ferrite-core/version/Mc6hHgQU
