### ISSUE TITLE
Crash on launch on Fabric 1.21.4

### ISSUE THREAD

**Issue by Poopooracoocoo** [malte0811/FerriteCore#180]
Tested with FerriteCore 7.1.0-hotfix ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric/files/5850347), [Modrinth](https://modrinth.com/mod/ferrite-core/version/7.1.0-hotfix-fabric)) on Fabric on MC 1.21.4

[latest.log](https://github.com/user-attachments/files/18049102/latest.log)
[crash-2024-12-08_03.11.01-client.txt](https://github.com/user-attachments/files/18049108/crash-2024-12-08_03.11.01-client.txt)

**Comment by Yamato320** [comment]
When I use Ferrite-core the game freezes when starting Minecraft. 😔

**Comment by SepticWelsh** [comment]
Same problem here, idk why this happens

**Comment by malte0811** [comment]
I have uploaded a new build for Fabric (7.1.1). The code is identical, but apparently there is a mapping issue that prevents the old build from working on 21.4. On Neo this mapping issue does not exist, so I did not upload new builds there.
