### ISSUE TITLE
Changes to Vanilla

### ISSUE THREAD

**Issue by overthinkinn** [malte0811/FerriteCore#181]
Does your mod change any aspects of vanilla Minecraft? And if not, why is it not allowed on MCSR? I searched and looked, and you haven't commented anywhere on whether your mod changes any aspects of vanilla. That's quite strange

**Comment by malte0811** [comment]
To my knowledge it does not change any vanilla behavior. If it does, that's a bug and should be reported. I do not know what MCSR is, so I do not know how to answer that part of the question.

**Comment by overthinkinn** [comment]
> To my knowledge it does not change any vanilla behavior. If it does, that's a bug and should be reported. I do not know what MCSR is, so I do not know how to answer that part of the question.

MCSR - Minecraft Speedrun, sorry about that
