### ISSUE TITLE
FerriteCore 1.17 is incompatible with Hydrogen 1.17

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [malte0811/FerriteCore#20]
When I remove either Hydrogen (0.3.0) or FerriteCore (3.0.0), the game launches fine. Here is a crash report with just Hydrogen and FerriteCore on Fabric 1.17: https://gist.github.com/DragonEggBedrockBreaking/576caba331baa1ac02da1220f4da05a9

**Comment by malte0811** [comment]
I should have expected this… Disable `modelResourceLocations` for now, the fix will probably be to do exactly that automatically. Hydrogen implemented "something" related to `ModelResourceLocation`s/`ModelIdentifier`s, I expect it's roughly the same as what I have in FC.

**Comment by srnyx** [comment]
On CurseForge you say "The only known incompatibility was Hydrogen, which is fully compatible with FC 2.0.4 and above."
But, they work fine for me with Hydrogen v0.2.0 and FerritCore v2.0.5

**Comment by malte0811** [comment]
Fixed in 9347388de2b2b8e81b3d44f489891f01484c90e4
