### ISSUE TITLE
Crash while tesselating block model

### ISSUE THREAD

**Issue by Kenny-Hui** [malte0811/FerriteCore#24]
With a combination of OptiFabric, FerriteCore and [Minecraft Transit Mod](https://github.com/jonafanho/Minecraft-Transit-Railway), the game will have a chance of crashing when Minecraft Transit Mod's **Automatic Platform Gates** opens.

This seems like a separate issue and is unrelated to FerriteCore, but I can no longer reproduce the crash after removing FerriteCore.
[Crash report](https://github.com/malte0811/FerriteCore/files/7020917/crash-report.txt)

FerriteCore Config:
`replaceNeighborLookup = true`
`replacePropertyMap = true`
`cacheMultipartPredicates = true`
`modelResourceLocations = true`
`multipartDeduplication = true`
`blockstateCacheDeduplication = true`
`bakedQuadDeduplication = true`
`compactFastMap = false`
`populateNeighborTable = true`

Here's what some other modder has to say (Which I don't quite understand):
![image](https://user-images.githubusercontent.com/28094366/130222521-c31aed82-14c1-42ac-872b-9d88ed79b850.png)

Is there any chance this could be resolved? Or are we stuck with this crash

**Comment by malte0811** [comment]
I have at least a general idea on what's causing this (a race condition on the cache used for multipart models), but I need to look into it in more detail. If my guess is right the vanilla code for multipart models is even more stupid than I thought. For now disabling `multipartDeduplication` in the config might "fix" it.
