### ISSUE TITLE
Incompatible With Iris

### ISSUE THREAD

**Issue by Luracasmus** [malte0811/FerriteCore#25]
When using FerriteCore and [Iris](https://modrinth.com/mod/iris/version/lAEtBzCu), CPU usage is 100% and the loading screen keeps appearing and disappearing when starting the game

[latest.log](https://github.com/malte0811/FerriteCore/files/7027277/latest.log)

I couldn't upload the entire latest.log as it was 49 MB

**Comment by malte0811** [comment]
It's actually Sodium and not Iris that's incompatible as far as I can tell, I'll fix this later today.

**Comment by malte0811** [comment]
I should probably mention this: With a reasonably recent build of sodium (anything after June 15th) you can safely use the previous build of FerriteCore, Sdoium also has a fix for #24.

**Comment by malte0811** [comment]
1.16.5: https://modrinth.com/mod/ferrite-core/version/2XHUVaPQ  
1.17.1: https://modrinth.com/mod/ferrite-core/version/HjttFjoa

CurseForge is down right now, I'll upload the builds there (and the corresponding Forge build) tomorrow, assuming it's back then.

**Comment by srnyx** [comment]
> CurseForge is down right now, I'll upload the builds there (and the corresponding Forge build) tomorrow, assuming it's back then.

Of course it is, when is it not?
