### ISSUE TITLE
Might wanna build with Java 16 instead of Java 11 cuz 1.17 is java 16

### ISSUE THREAD

**Issue by Eshanepicfighter** [malte0811/FerriteCore#28]
Build.yaml is currently 
https://raw.githubusercontent.com/malte0811/FerriteCore/main/.github/workflows/build.yaml
Build.yaml should be
name: Build and publish as artifact
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
         distribution: 'adopt'
          java-version: 16
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            forge/build/libs/ferritecore-*-forge.jar
            fabric/build/libs/ferritecore-*-fabric.jar

**Comment by malte0811** [comment]
That's for the `main` branch, which is on 1.16.5 (until Forge gets Mixins on 1.17 at least). The [1.17 build.yaml](https://github.com/malte0811/FerriteCore/blob/1.17/.github/workflows/build.yaml) already uses Java 16.
