### ISSUE TITLE
3.0.2 loadingscreen blinking

### ISSUE THREAD

**Issue by rasmus123d** [malte0811/FerriteCore#29]
when i run with this mod on version 3.0.2 for 1.17.1 its rapidly blinking when launching minecraft

**Comment by RealCamar** [comment]
Getting the same issue to, currently investigating what is causing this

**Comment by malte0811** [comment]
This is most likely a duplicate of #25 (incompatibility with sodium, even though the title says Iris). I only uploaded fixed builds to modrinth yesterday since CF was down, I'll upload them there now.
