### ISSUE TITLE
When using the mod with the Quark mod, the client crashes

### ISSUE THREAD

**Issue by XionioXMaster** [malte0811/FerriteCore#34]
As soon as you step on the Luke or the button, the client departs!

**Comment by XionioXMaster** [comment]
However, this does not work on localhost

**Comment by malte0811** [comment]
1. Maybe provide *any* kind of details?
2. I had a look at your reports to quark, if this is the same issue: Gravit Launcher is providing the wrong version of Guava, which does not work with FerriteCore. This is on Gravit to fix, not Quark or FC.
