### ISSUE TITLE
Error on server launch

### ISSUE THREAD

**Issue by xanthian** [malte0811/FerriteCore#35]
Unsure if this is anything relevant (or what it even means) but figured I'd add it here.
No obvious impact on the server.

[main/WARN]: @Mixin target net/minecraft/class_4970$class_4971$class_3752 is public in ferritecore.blockstatecache.mixin.json:BlockStateCacheMixin and should be specified in value

Server Version 1.17.1
Running Fabric 0.7.4 (latest)
Server mods in use :

architectury-2.5.30-fabric.jar
carpet-extra-1.17.1-1.4.43.jar
cloth-config-5.0.38-fabric.jar
clumps-fabric-1.17.1-7.0.7.jar
dualriders-1.17-1.0.5.jar
editsign-1.17.1-2.2.4.jar
extshape-1.2.6-mc1.17+.jar
fabric-api-0.40.1+1.17.jar
fabric-carpet-1.17.1-1.4.47+v210924.jar
fabric-language-kotlin-1.6.4+kotlin.1.5.30.jar
ferritecore-3.1.0-fabric.jar
full-slabs-3.1.3.jar
hydrogen-fabric-mc1.17.1-0.3.jar
literally-chunk-loader-1.17.1-2.0.3.jar
lithium-fabric-mc1.17.1-0.7.4.jar
observable-0.1.2-1.17-fabric.jar
servux-fabric-1.17.0-0.1.0.jar
starlight-1.0.0+fabric.73f6d37.jar
tomsstorage-1.1.17.jar
wthit-fabric-3.9.1.jar
xaerosworldmap_1.17.1_fabric_1.17.1.jar
xaeros_minimap_21.17.1_fabric_1.17.1.jar

**Comment by urolithicrogue** [comment]
can confirm my server had the same issue on ferritecore 3.1.0, i also have some notes  and this is what i have noticed both in singleplayer and on my server mod list is close to the same as the prior person

1 flying or using creative gets lots of jerkiness while moving especially while moving through chunks

2 fps is much lower with 3.0.3 it was around 128 but with 3.0.1 fps goes to 80 or lower

3 also 3.0.1 appears to be unstable as the server would crash within a range of 10 to 15 minutes of running consistently

4 tried using the newest fabric version 0.11.7 with very little to no improvements regarding stability but appears to be somewhat smoother in chunks but not by a lot

**Comment by malte0811** [comment]
@xanthian That warning isn't a problem, and it's also a false positive (the class isn't actually public). I assume some mod is making it public at runtime, but that doesn't make it possible to specify the target "in value".

@urolithicrogue I've marked your comment as off-topic. First of all, all of your points are unrelated to this issue (which is purely about the log warning). Secondly, none of your points has any information that would help me fix the issues. For the first and second point I'd want profiling data (e.g. using Spark), for the third I can't do anything without a crashlog and the last one doesn't really seem relevant at all.
