### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by boasbakker** [malte0811/FerriteCore#37]
Are you planning to make versions for 1.18 snapshots?

**Comment by DragonEggBedrockBreaking** [comment]
What about now, considering 1.18 will be released in a few days?

**Comment by malte0811** [comment]
I'm already working on the update, the primary effort is checking that my assumptions on vanilla code are still valid (and that's something I want to do myself). Fabric release will *probably* happen some time over the next week, depending on how busy I am with other things.
