### ISSUE TITLE
Crash Upon Start

### ISSUE THREAD

**Issue by ReeCodes** [malte0811/FerriteCore#38]
https://mclo.gs/dFUvzvH

**Comment by ReeCodes** [comment]
latest.log
https://mclo.gs/Db1Ao0X

**Comment by malte0811** [comment]
Can you upload a debug.log as well? Somehow one of my Mixins isn't applying at all, and I don't see why it wouldn't yet.

**Comment by ReeCodes** [comment]
debug.log
https://mclo.gs/b04pwy9

**Comment by malte0811** [comment]
Is this pack available somewhere? I assume it's a modified version of [this](https://www.curseforge.com/minecraft/modpacks/crazy-crave-5/files/3499492)? If so, what do I need to change? I have one idea what might be causing this, and debugging that "remotely" is not going to be easy.

**Comment by ReeCodes** [comment]
I came back to this problem - startup crash (the window popped up saying its ferritecore...) :

**Steps to reproduce the behavior**
- Start MC

**Expected behavior**
Run flawlessly

**Mod version**
ferritecore-2.1.0-forge.jar

** Logs **
[Latest log] https://mclo.gs/FpbVpBM

**Comment by ReeCodes** [comment]
Crash log: https://mclo.gs/VqQ0uau

**Comment by malte0811** [comment]
This is still very relevant:
> Is this pack available somewhere? I assume it's a modified version of [this](https://www.curseforge.com/minecraft/modpacks/crazy-crave-5/files/3499492)? If so, what do I need to change? I have one idea what might be causing this, and debugging that "remotely" is not going to be easy.

You'll either need to do a binary search yourself (and hope it's a single other mods causing this) or give me some way of debugging this properly locally.

**Comment by ReeCodes** [comment]
https://www.curseforge.com/minecraft/modpacks/crazy-crave-5
[performant-common.toml] https://mclo.gs/52GLXMv (overwrite the Performant config with this)

**Comment by ReeCodes** [comment]
![image](https://user-images.githubusercontent.com/50622547/147008802-3a10333d-9b35-4a7e-98d3-5c73a74a6e5f.png)

**Comment by malte0811** [comment]
After some local debugging and talking to someaddons, this is a bug in Performant. I'll close this issue, further discussion should go into someaddons/performant_issues#211 (unless it turns out there's some problem on my end as well).
