### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by AmibeSkyfy16** [malte0811/FerriteCore#42]
I have this error on starting server: https://pastebin.com/v2PCp3cD
Im using fabric loader 0.12.8, java 16 and curseforge launcher

**Comment by AmibeSkyfy16** [comment]
It seems to be fixed, the problem occurs only at the first launch

**Comment by malte0811** [comment]
Fixed on 1.18 by the above commit (I hope). I'll probably backport the fix to 1.16 later, but I'll be dropping support for 1.17 since porting to 1.18 should be easy for most mods.
