### ISSUE TITLE
Version 2.1.0 for 1.16.5 does not work with java 17

### ISSUE THREAD

**Issue by NotADinosaur** [malte0811/FerriteCore#43]
log: https://paste.ee/p/02fUO

**Comment by malte0811** [comment]
The error is the same as in #42, so it isn't an issue with Java 17 specifically. I'm not sure why these are popping up now, I've got a potential fix I'll probably release today.

**Comment by NotADinosaur** [comment]
nvm I'm an idiot, i forgot that it needs fabric api. It loads fine with that.
I was trying to isolate it to see if it was an incompatibility with one of my other mods, but I isolated it too much and it crashed for a different reason. It seems to be incompatible with [RandomPatches](https://github.com/TheRandomLabs/RandomPatches)
Log [here](https://paste.ee/p/YdTuV)

**Comment by NotADinosaur** [comment]
I remembered using the two mods together before, so I did some further testing: RandomPatches and FerriteCore are incompatible when using fabric api 0.42.0. Using fabric api 0.41.3 earlier, the two mods work together. Should I report this to the fabric api issues page?

**Comment by malte0811** [comment]
Thanks for narrowing this down! I'm able to reproduce it with those mods, I'll do some debugging and then report it to whatever mod I decide is causing the issue (or fix it if it turns out to be FerriteCore).

**Comment by malte0811** [comment]
https://github.com/TheRandomLabs/RandomPatches/issues/252
