### ISSUE TITLE
Ferrite Core Fabric 1.18 crashes upon startup

### ISSUE THREAD

**Issue by shadei** [malte0811/FerriteCore#44]
i am on mac, and whenever i launch Minecraft with ferrite core installed it crashes immediately. here is a link to the crash logs:
[debug.log](https://paste.ee/p/vNOkf) [latest.log](https://paste.ee/p/MO4cq#e79JbAuGgaJZ1zbhqXEPVncgDozQtHuI)

**Comment by malte0811** [comment]
You're using FerriteCore 2.1.0, which is for Minecraft 1.16, on Minecraft 1.18. You'll need to use 4.0.0 on 1.18.

**Comment by abatewongc** [comment]
FYI, I also ran into this, since 2.1.0 is considered the 'main' file and is pinned at the top of the files tab in Curseforge.
