### ISSUE TITLE
Crash upon start of server on 1.18 with java 17

### ISSUE THREAD

**Issue by ShadowThijs** [malte0811/FerriteCore#45]
Whenever I start my 1.18 server with FerriteCore4.0.0 I keep getting the same error about Java 17. 
Here is the error log: https://pastebin.com/EdqdSdcg
Is this on my end or is this an issue with the mod itself?

**Comment by xpopy** [comment]
Same issue here.
`The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))` is the error
I have been getting this with other mods too, like Starlight for example. No idea how to run the mod

**Comment by malte0811** [comment]
This was actually a bug in the Fabric installer: https://github.com/FabricMC/fabric-installer/issues/94. Reinstalling the server with the latest installer should fix it.
