### ISSUE TITLE
Crash with optifine and phantom attacks

### ISSUE THREAD

**Issue by m-sarabi** [malte0811/FerriteCore#48]
When using this mod and optifine on client, as soon as a phantom attacks me game freeze and crash (playing on a vanilla server that do not have this mod)
I tried with only tis mod and with only optifine and they both work fine. It only happens when having optifine and optifabric

**Comment by malte0811** [comment]
Please upload the crashlog to https://pastebin.com or similar.

**Comment by malte0811** [comment]
Closing due to lack of response
