### ISSUE TITLE
Crash with Friends&Foes

### ISSUE THREAD

**Issue by Faboslav** [malte0811/FerriteCore#49]
When i run project with my mod Friends&Foes,  game wont start, but i cant tell what is wrong. I tried to remove all new mixins opposite to my prev version of the mod, but i did not have any success with that.

[crash-2022-01-17_09.34.09-client.txt](https://github.com/malte0811/FerriteCore/files/7880296/crash-2022-01-17_09.34.09-client.txt).

**Comment by Faboslav** [comment]
Okay after more investigation crash occurs if i am using `EarlyRiser`:

```
import com.chocohead.mm.api.ClassTinkerers;
import net.fabricmc.loader.api.FabricLoader;
import net.fabricmc.loader.api.MappingResolver;

public class EarlyRiser implements Runnable
{
	@Override
	public void run() {
		if (FriendsAndFoes.CONFIG.enableIllusionerInRaids) {
			MappingResolver remapper = FabricLoader.getInstance().getMappingResolver();

			String Raid = remapper.mapClassName("intermediary", "net.minecraft.class_3765$class_3766");
			String EntityType = 'L' + remapper.mapClassName("intermediary", "net.minecraft.class_1299") + ';';

			ClassTinkerers
				.enumBuilder(Raid, EntityType, int[].class)
				.addEnum("ILLUSIONER", () -> new Object[]{net.minecraft.entity.EntityType.ILLUSIONER, new int[]{0, 0, 0, 0, 0, 0, 1, 1}})
				.build();
		}
	}
}
```

**Comment by malte0811** [comment]
From [here](https://github.com/Chocohead/Fabric-ASM/blob/239e122a532ba8cabf0714df2aa9fdd80f2082d4/README.md#navigating-the-entrance):
 > The earliness that extensions require poses potential pitfalls from class loading. Given the main launch class will get to be resolved, any accidental reference to a class that might have Mixins that need to be applied will certainly result in a sad time. As a consequence there's a great need to be careful the for classes that might be loaded by an Early Riser.

In particular, you are loading the class `FriendsAndFoes`, which in turn loads `OmegaConfig`, which loads `Identifier` aka `class_1091`. I have an accessor Mixin into `Identifier`/`ResourceLocation`, so the result is what Chocohead refers to as "a sad time".

**Comment by Faboslav** [comment]
So is there any solution for that?

**Comment by Faboslav** [comment]
Anyway thank you very much for the explanation!
