### ISSUE TITLE
Latest FerriteCore touches resourepack init or some sort, bootloops the game

### ISSUE THREAD

**Issue by Neubulae** [malte0811/FerriteCore#5]
https://hatebin.com/hyfhziwkjb

**Comment by malte0811** [comment]
Can you upload a full modlist and the complete log? I'm unable to reproduce this so far.

**Comment by Neubulae** [comment]
https://hatebin.com/dvfkyhqeot

**Comment by Neubulae** [comment]
[2021-02-25-6.log](https://github.com/malte0811/FerriteCore/files/6048572/2021-02-25-6.log)
