### ISSUE TITLE
[1.18.1] Crash on start: "Mixin transformation of net.minecraft.class_310 failed"

### ISSUE THREAD

**Issue by ExperiBass** [malte0811/FerriteCore#51]
[latest.log](https://github.com/malte0811/FerriteCore/files/8007398/latest.log)

I installed FerriteCore from CurseForge.

**Comment by malte0811** [comment]
You installed FerriteCore 2.1.0, which is for 1.16. You need FerriteCore 4.0.0.

**Comment by ExperiBass** [comment]
goddammit, the big download button grabbed the 1.16 one.
