### ISSUE TITLE
Crash at world loading 1.18.1

### ISSUE THREAD

**Issue by agentwolf88** [malte0811/FerriteCore#52]
https://bytebin.lucko.me/n6eQpzi2bh

**Comment by Dorrivix** [comment]
I'm getting the same error

**Comment by malte0811** [comment]
I'll look into this tomorrow, for now you can disable `smallThreadingDetector` in the FerriteCore config as a workaround. Can one (or even both) of you upload a full log (latest.log)? That should have information on the "other half" of the crash.

**Comment by agentwolf88** [comment]
NP

Here is the latest log.
[latest.log](https://github.com/malte0811/FerriteCore/files/8008892/latest.log)

**Comment by Panderine** [comment]
Same, rekon I have several mods in the server crashing.

**Comment by Panderine** [comment]
Also, my crash is on fabric and not on server load but after a while

**Comment by isaaclepes** [comment]
I have the same issue as well

Crash log: https://gist.github.com/isaaclepes/101552a456b1eff0ba5e03c4b7f63f88
Debug Log: https://gist.github.com/isaaclepes/cdf6d0e3df44628746735cf86484e5cd
latest log: https://gist.github.com/isaaclepes/e5f1396f653d1050afc1f24245dcbd73

**Comment by neonjuno** [comment]
I had the same problem when trying to load into a newly created world, but the problem didn't ocur when entering a superflat world.

**Comment by SzczurekYT** [comment]
Also got the error, Temporary fix works, thanks for sharing it,

**Comment by malte0811** [comment]
> I had the same problem when trying to load into a newly created world, but the problem didn't ocur when entering a superflat world.

And that's the problem, I only tested the second one in dev… Even though it's clear in hindsight that worldgen is a much more important test case.

I'll remove the `SmallThreadingDetector` code for now; the problem is that I missed an important "valid" case and am reporting it as a race condition. I think I can fix it, but it's not trivial and I won't have the time for that in the next 1.5 weeks or so.

**Comment by malte0811** [comment]
Reverted the commit adding the feature for now, I'll revisit this when I have some time:  
Commit: 277b25f83b1afe4baeca69e46ce0a084692f7f8d  
CF (Forge): https://www.curseforge.com/minecraft/mc-mods/ferritecore/files/3638442  
CF (Fabric): https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric/files/3638441  
Modrinth (Fabric): https://modrinth.com/mod/ferrite-core/version/c9p5gemS
