### ISSUE TITLE
crash on creating new world

### ISSUE THREAD

**Issue by Flame115** [malte0811/FerriteCore#54]
https://pastebin.com/RZZ5aHyN

**Comment by freopt** [comment]
getting same crash on trying to load a world, forge

**Comment by aerialspring** [comment]
Same, after updating to 4.1.0
https://paste.ee/p/vtCqW

**Comment by Camawama** [comment]
Yep, new update crashing on world creation :)

**Comment by esotericist** [comment]
also experienced this. but at least rolling back to 4.0 gets things going again.

**Comment by itsdinkd** [comment]
https://crashy.net/iMpKE44C1ewbthYK0pPw

https://bytebin.lucko.me/DdNkFS5qca

2 players have also crashed.

**Comment by malte0811** [comment]
Duplicate of #52
