### ISSUE TITLE
Versions 4.1.0 and 4.1.1 both crash on launch (no crash report/incompatibilities detected by fabric)

### ISSUE THREAD

**Issue by Slooshie1** [malte0811/FerriteCore#56]
I have a looooong list of mods, and I just spent like half an hour trying to Thanos-method my mods trying to find out what was crashing my game on startup, and I finally found out it was caused by ferrite core 4.1.1, so I tried 4.1.0 with the same results, but I tried with 4.0.0 and it works fine, so frankly I'm too lazy to do all of that again just to see what mod isn't compatible with version 4.1.0 and later, at least not right now. If I try to Thanos-method my mods again with version 4.1.1 always enabled, I'll update this thread, but for now this thread will just be as an unknown incompatibility.

**Comment by malte0811** [comment]
Can you at least upload a full log?

**Comment by Slooshie1** [comment]
[latest.log](https://github.com/malte0811/FerriteCore/files/8053011/latest.log)

**Comment by malte0811** [comment]
And that already has all the information I need. Hydrogen is no longer supported as it has been [abandoned by Jelly/Caffeine](https://github.com/CaffeineMC/hydrogen-fabric/#status) and will never be officially released on 1.18.x.
