### ISSUE TITLE
Are Hydrogen patches comming to FerriteCore?

### ISSUE THREAD

**Issue by PweSol** [malte0811/FerriteCore#57]
Since the latest version of FerriteCore is no longer compatible with Hydrogen and Hydrogen will no longer be updated, will the optimizations from it come to this or a different mod (such as Lithium)?

I'm not sure if it's worth it to stick with FerriteCore 4.0.0 and continue using Hydrogen, or if the latest dev updates on Lithium and FerriteCore outweigh the usage of Hydrogen.

**Comment by malte0811** [comment]
I won't be porting patches from Hydrogen, for 2 reasons:
1. I don't think H has any major improvements that don't have an equivalent in FC at this point, if you are aware of any I'd be happy to hear about them.
2. Even without the first point, I can't simply copy patches from H; at least not without more licensing trouble than I'm willing to go through.
