### ISSUE TITLE
[4.1.1 Forge] Crash with latest Selene Library

### ISSUE THREAD

**Issue by itsdinkd** [malte0811/FerriteCore#60]
After updating Supplementaries 3 and Selene (its library) to latest versions, dedicated server is crashing on load.

Crash log: https://gist.github.com/itsdinkd/8194eb1c86e85a8260b91239760887ec

**Comment by malte0811** [comment]
Can you check if it still crashes when you remove FC? I'll look into this properly tomorrow, but the crash doesn't look like the crash I'd expect here.

**Comment by malte0811** [comment]
Closing due to lack of response.
