### ISSUE TITLE
Lithium 0.7.8 neighbor table direct access

### ISSUE THREAD

**Issue by GunnyWaffle** [malte0811/FerriteCore#63]
[Lithium 0.7.8](https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.18.1-0.7.8) just released and it tripped the neighbor table crash/warning in FerriteCore.
`populateNeighborTable = true` works as advertised, so this isn't blocking.

**Comment by malte0811** [comment]
Update FerriteCore, this is not a problem with 4.1.0 and above.
