### ISSUE TITLE
v4.1.2 crash on startup

### ISSUE THREAD

**Issue by Diplotomodon** [malte0811/FerriteCore#64]
Only running Fabric API, Sodium/Iris, and Mod Menu alongside FerriteCore; game launches fine without it. I suspect 1.18.2 might be the issue - heard that it broke a lot of stuff behind the scenes for modders. If so, hopefully these logs help out with an update

[crash-2022-03-01_22.02.58-client.txt](https://github.com/malte0811/FerriteCore/files/8166351/crash-2022-03-01_22.02.58-client.txt)

**Comment by malte0811** [comment]
FC 4.2.0 for MC 1.18.2 is out now.
