### ISSUE TITLE
Radium Reforged compatibility 

### ISSUE THREAD

**Issue by Atlantispy** [malte0811/FerriteCore#66]
Hi,

Can you please implement a similar thing to switch off FC's thread detector thing when Radium Reforged is installed, as it's the forge equivalent

Thanks

**Comment by malte0811** [comment]
That should already work. I'm checking if `me.jellysquid.mods.lithium.common.LithiumMod` exists, which it should in Radium.
> as it's the forge equivalent

"The" is putting it a bit strongly. It's one of various different Forge ports, I don't intend to add specific support for every one of them.
