### ISSUE TITLE
Crashed in 1.18.2, found in the logs to report it here

### ISSUE THREAD

**Issue by sulkysays** [malte0811/FerriteCore#67]
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly.

I can provide more if needed

**Comment by malte0811** [comment]
Yes, I'll need a full crashlog. That line by itself does not tell me much more than "it crashed".

**Comment by sulkysays** [comment]
[2022-03-05-1.log](https://github.com/malte0811/FerriteCore/files/8191424/2022-03-05-1.log)
Here you go - sorry I have lots of mods installed so you might need to sift through a lot

**Comment by malte0811** [comment]
That is definitely not the right log, that only has a crash related to starlight.

**Comment by KingCreeperz** [comment]
I am having this too!

**Comment by malte0811** [comment]
I'm closing this issue since so far no one has managed to provide a full crashlog of the correct crash. If you have a similar crash make sure you're using the most recent FC build and open a new issue with a full crashlog.
