### ISSUE TITLE
Implement Memory Leak Fix

### ISSUE THREAD

**Issue by RaptaG** [malte0811/FerriteCore#76]
Since this mod is about memory usage optimization, I believe implementing the [Memory Leak Fix mod](https://modrinth.com/mod/memoryleakfix) would offer some extra performance!

**Comment by Madis0** [comment]
Should be closed as the dev said it is out of scope for FerriteCore.

**Comment by malte0811** [comment]
I don't consider memory leaks out-of-scope for FC in general, but I don't just copy fixes from other mods.
