### ISSUE TITLE
[compatibility issue] Missing Faces when used with Subterranean Wilderness

### ISSUE THREAD

**Issue by stevensongren** [malte0811/FerriteCore#8]
When mod is installed with the subterranean wilderness mod on Forge 36.0.35, half blocks from the mod are missing sides, leaving holes in the world. I've also posted this issue on the other mod's github, hopefully we can get these two to place nice together :)
![Screenshot 2021-03-02 013314](https://user-images.githubusercontent.com/54342338/109628729-f0c6c000-7af7-11eb-96af-4753b4f8a92a.png)

REPRODUCE:

Create new instance in Curseforge launcher (Forge 36.0.35)
Install Subterranean Wilderness (SubWild-1.16.5-1.1.2.jar)
Install FerriteCore (ferritecore-2.0.1-forge)
Create new world, find cave

**Comment by malte0811** [comment]
Update FC, this was fixed in build 2.0.2 (but you should update all the way to 2.0.3).
