### ISSUE TITLE
1.19 Latest Forge Crash

### ISSUE THREAD

**Issue by LoxiGoose** [malte0811/FerriteCore#80]
Currently FerriteCore (Forge) crashes on the latest versions of Forge upon startup.

Minecraft Version: 1.19
Forge Version: 41.0.85
Mod Version: 5.0.0

Crash report
https://mclo.gs/qJp1syU

**Comment by malte0811** [comment]
Forge had a mass of breaking changes in a recent update, I'll look into fixing this in a couple of days (I'm quite busy IRL until Wednesday). The immediate crash should be easy, but I need to make sure they didin't change anything that breaks my optimizations.

**Comment by LoxiGoose** [comment]
Alright, thanks! I'll be waiting, take your time!

**Comment by cpm9** [comment]
I also have a crash with ferritecore on the latest forge (41.0.98) that I think is different than the one above here it is

[ferritecorecrash.txt](https://github.com/malte0811/FerriteCore/files/9098607/ferritecorecrash.txt)

**Comment by malte0811** [comment]
@cpm9 that's not related to the Forge update; it looks like FC is also incompatible with Radium right now. I'll fix that in the next update as well.
