### ISSUE TITLE
Slabs adjacent to snow layers get culled incorrectly

### ISSUE THREAD

**Issue by dromedar17** [malte0811/FerriteCore#9]
A bottom slab next to 1 layer high snow becomes partially invisible (the side facing the snow doesn't get rendered). This also happens for snow layers of different height next to each other if the difference in height is 7 pixels and neither is a full block.

This is on Forge 36.0.43

**Comment by malte0811** [comment]
You did not specify what version of FC you're using. I assume it's 2.0.1, since this issue was fixed in 2.0.2. If you're actually experiencing this on the latest build (2.0.3) please comment on the closed issue, I'll reopen it in that case.
