### ISSUE TITLE
1.19.2 Crash with Radium

### ISSUE THREAD

**Issue by Dradon7** [malte0811/FerriteCore#91]
Forge 43.1.3
Radium 0.8.2
FerriteCore 5.0.1

Both mods individually boot up fine individually and with other mods, but together they crash.

Latest Log with a fresh instance with just these two mods: [latest.log](https://github.com/malte0811/FerriteCore/files/9434742/latest.log)

Lemme know if you need anything else.

**Comment by malte0811** [comment]
See https://github.com/malte0811/FerriteCore/issues/80#issuecomment-1184121400.
