### ISSUE TITLE
question about warning - fabric

### ISSUE THREAD

**Issue by FixingGlobe** [malte0811/FerriteCore#92]
Hi,
Sorry to bother you and I don't seem to find much information but when I start my quilt server with qfabi I do get the following warning.
[main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
Is this intentional behavior or something which could be an incompatibility with another mod?

**Comment by Felix14-v2** [comment]
This is a compatibility solution, mixin disabling caused by another mod. It's not critical, I guess.

**Comment by FixingGlobe** [comment]
Found something more it will do one override for Lithium but I haven't found any issues so far.

**Comment by malte0811** [comment]
This is intentional. Lithium has some memory usage optimizations for blockstates (came from Hydrogen), but FerriteCore's optimizations use even less memory and are typically more performant as well. You can't use both optimizations at once, so FerriteCore disables Li's optimization there.
