### ISSUE TITLE
Error launching server. report to https://github.com/malte0811/FerriteCore/issues

### ISSUE THREAD

**Issue by Zelioth** [malte0811/FerriteCore#95]
In the process of updating my server and this issue appeared. what does it mean? I have no clue?

MC 1.19.2
Forge 43.1.34
Pack : Friends United 1.19.2
[latest.log](https://github.com/malte0811/FerriteCore/files/9742953/latest.log)

**Comment by malte0811** [comment]
This is likely a compatibility issue with Canary (a lithium port). For now you can add `mixin.alloc.blockstate=false` to `config/canary.properties`.

Reference for myself: https://github.com/AbdElAziz333/Canary/blob/e4c887fd5fe072842dc8bd4a7546758dbe954fc5/src/main/java/com/abdelaziz/canary/common/config/CanaryConfig.java#L305

**Comment by malte0811** [comment]
Actually, that doesn't quite explain things. Canary tries to disable that option automatically when FerriteCore is installed, so something else seems to be broken here. Can you upload the debug.log as well? The latest.log doesn't have any relevant data, and my previous comment was mostly an educated guess.

**Comment by malte0811** [comment]
See https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397.
